insert into public.clients (
  id,
  tenant_id,
  full_name,
  document_id,
  email,
  phone,
  whatsapp,
  address,
  lead_source,
  bank_name,
  service_status,
  signed_contract,
  legal_viability_score,
  fees_label,
  documents_sent,
  notes,
  ia_context,
  linked_cases,
  linked_documents,
  timeline
)
values
  (
    'cl-001',
    '11111111-1111-1111-1111-111111111111',
    'Mariana Torres Lima',
    '284.115.990-41',
    'mariana.torres@cliente.com.br',
    '(11) 98421-1190',
    '(11) 98421-1190',
    'Rua Alvorada, 182, Vila Olimpia, Sao Paulo/SP',
    'Instagram',
    'Banco Pan',
    'active',
    true,
    9.1,
    'R$ 8.500 + 20% sobre exito',
    12,
    'Cliente relata contratacao por correspondente sem explicacao adequada sobre CET e seguro embutido.',
    'LexIA identificou sinais de venda casada e alta aderencia a tese revisional com pedido de repeticao de indebito.',
    '[{"id":"case-101","title":"Revisional de financiamento de veiculo","status":"Em analise inicial","thesis":"Juros abusivos e seguro embutido"}]'::jsonb,
    '["Contrato bancario","Planilha de parcelas","Extratos","Comprovante de renda"]'::jsonb,
    '["Lead qualificado via Instagram com score inicial 8.8","Contrato e documentos recebidos","Triagem da LexIA concluida com risco processual medio-baixo"]'::jsonb
  ),
  (
    'cl-002',
    '11111111-1111-1111-1111-111111111111',
    'Carlos Henrique Duarte',
    '317.558.120-08',
    'carlos.duarte@cliente.com.br',
    '(21) 98810-4422',
    '(21) 98810-4422',
    'Av. das Americas, 9600, Barra da Tijuca, Rio de Janeiro/RJ',
    'Indicacao',
    'Itau',
    'waiting-docs',
    false,
    7.4,
    'Proposta em aprovacao',
    5,
    'Possivel fraude bancaria por PIX. Falta boletim de ocorrencia e comprovantes complementares.',
    'LexIA recomenda reforcar checklist documental e validar cronologia das transferencias antes da definicao final da tese.',
    '[{"id":"case-205","title":"Fraude bancaria via PIX","status":"Aguardando documentos","thesis":"Falha de seguranca e dano moral"}]'::jsonb,
    '["Comprovantes PIX","Atendimento bancario","Capturas de tela"]'::jsonb,
    '["Cliente entrou por indicacao de ex-cliente","Atendimento inicial realizado pelo time comercial-juridico","Checklist de documentos enviado pelo escritorio"]'::jsonb
  ),
  (
    'cl-003',
    '11111111-1111-1111-1111-111111111111',
    'Patricia Gomes Araujo',
    '44.118.225/0001-10',
    'financeiro@araujologistica.com.br',
    '(31) 3339-7788',
    '(31) 99655-1199',
    'Rua Paraiba, 455, Funcionarios, Belo Horizonte/MG',
    'Google Ads',
    'Santander',
    'active',
    true,
    8.6,
    'R$ 14.000 + exito escalonado',
    18,
    'Cliente modelo para dois fluxos complementares do escritorio: fraude consignada / RMC e busca e apreensao.',
    'LexIA aponta que este cliente pode demonstrar tanto o modelo de fraude consignada quanto o modelo de busca e apreensao, mantendo a leitura clara por caso.',
    '[{"id":"case-311","title":"Fraude consignada / RMC","status":"Peca inicial em preparacao","thesis":"Desconto indevido em cartao consignado"},{"id":"case-312","title":"Busca e apreensao de veiculo","status":"Documentacao completa","thesis":"Mora controvertida e preservacao do veiculo"}]'::jsonb,
    '["Contrato do cartao consignado","Notificacao de busca e apreensao","Extrato do beneficio","Documento do veiculo"]'::jsonb,
    '["Lead convertido por campanha de alta intencao","Contrato assinado no mesmo dia da proposta","Time recebeu documentacao complementar da pessoa fisica"]'::jsonb
  )
on conflict (id) do update
set
  full_name = excluded.full_name,
  document_id = excluded.document_id,
  email = excluded.email,
  phone = excluded.phone,
  whatsapp = excluded.whatsapp,
  address = excluded.address,
  lead_source = excluded.lead_source,
  bank_name = excluded.bank_name,
  service_status = excluded.service_status,
  signed_contract = excluded.signed_contract,
  legal_viability_score = excluded.legal_viability_score,
  fees_label = excluded.fees_label,
  documents_sent = excluded.documents_sent,
  notes = excluded.notes,
  ia_context = excluded.ia_context,
  linked_cases = excluded.linked_cases,
  linked_documents = excluded.linked_documents,
  timeline = excluded.timeline,
  updated_at = timezone('utc', now());
