insert into public.cases (
  id,
  tenant_id,
  client_id,
  title,
  bank_name,
  process_number,
  contract_number,
  claim_type,
  stage,
  status,
  amount_in_dispute,
  estimated_value,
  main_thesis,
  legal_risk,
  suggested_strategy,
  owner_label,
  niche,
  linked_documents,
  linked_tasks,
  linked_deadlines,
  lexia_insights,
  workflow_state,
  checklist_state
)
values
  (
    'case-101',
    '11111111-1111-1111-1111-111111111111',
    'cl-001',
    'Revisional de financiamento de veiculo',
    'Banco Pan',
    '1008421-19.2026.8.26.0100',
    'PAN-44-99281',
    'acao_revisional',
    'Analise inicial',
    'active',
    68400,
    32200,
    'Juros abusivos e seguro embutido',
    'medium',
    'Consolidar memoria de calculo, destacar venda casada e estruturar pedido de revisao contratual com tutela para suspensao de cobranca excessiva.',
    'Dra. Helena Siqueira',
    'revisional',
    '["Contrato bancario","Planilha de parcelas","Extratos","Comprovante de renda"]'::jsonb,
    '["Revisar memoria de calculo","Validar clausula de seguro embutido","Preparar peticao inicial"]'::jsonb,
    '["Coletar documentos complementares ate 14/04/2026","Aprovar estrategia interna ate 16/04/2026"]'::jsonb,
    '["Boa aderencia a tese revisional com foco em venda casada.","Ha espaco para pedido cumulativo de repeticao de indebito.","Cliente tem documentacao suficiente para primeira peca."]'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    'case-205',
    '11111111-1111-1111-1111-111111111111',
    'cl-002',
    'Fraude bancaria via PIX',
    'Itau',
    '5011274-65.2026.8.19.0001',
    'PIX-FRD-1180',
    'fraude_bancaria',
    'Aguardando documentos',
    'awaiting-action',
    18750,
    41000,
    'Falha de seguranca e dano moral',
    'medium',
    'Fechar cronologia do evento, reforcar prova documental e estruturar narrativa de falha na seguranca da operacao PIX.',
    'Dr. Caio Nascimento',
    'fraude',
    '["Comprovantes PIX","Atendimento bancario","Capturas de tela"]'::jsonb,
    '["Cobrar boletim de ocorrencia","Solicitar comprovante bancario detalhado","Montar cronologia do golpe"]'::jsonb,
    '["Revisar pendencias documentais em 11/04/2026"]'::jsonb,
    '["Sem boletim de ocorrencia, a narrativa probatoria fica fragil.","A tese principal permanece viavel se a cronologia for bem consolidada."]'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    'case-311',
    '11111111-1111-1111-1111-111111111111',
    'cl-003',
    'Capital de giro com juros abusivos',
    'Santander',
    '7012844-11.2026.8.13.0024',
    'CCB-88372',
    'juros_abusivos',
    'Peca inicial em preparacao',
    'active',
    248000,
    118000,
    'Capitalizacao mensal indevida',
    'low',
    'Combinar revisao contratual com pedido de tutela para limitar cobranca e reforcar a leitura economica do capital de giro.',
    'Dra. Julia Ramalho',
    'revisional',
    '["CCB","Extratos da conta","Email de cobranca","Comprovantes bancarios","Contrato social"]'::jsonb,
    '["Finalizar fatos resumidos","Conferir planilha de encargos","Revisar fundamentos da inicial"]'::jsonb,
    '["Submeter minuta para revisao em 15/04/2026","Validar anexos ate 17/04/2026"]'::jsonb,
    '["Caso com boa combinacao entre tese economica e prova documental.","Recomendavel destacar capitalizacao mensal e CET total no resumo executivo."]'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  ),
  (
    'case-312',
    '11111111-1111-1111-1111-111111111111',
    'cl-003',
    'Negativacao indevida vinculada ao contrato',
    'Santander',
    '7012855-49.2026.8.13.0024',
    'NEG-55210',
    'negativacao_indevida',
    'Documentacao completa',
    'active',
    32000,
    24000,
    'Suspensao de cobranca e danos',
    'low',
    'Estruturar urgencia na retirada da restricao e combinar pedido declaratorio com danos morais bancarios.',
    'Dra. Julia Ramalho',
    'revisional',
    '["Email de cobranca","Comprovantes bancarios","Notificacao de negativacao"]'::jsonb,
    '["Validar prova da negativacao","Fechar pedido de tutela","Revisar danos morais"]'::jsonb,
    '["Consolidar anexos ate 13/04/2026"]'::jsonb,
    '["Caso apto para narrativa objetiva com pedido urgente.","Documentacao completa melhora o potencial de tutela."]'::jsonb,
    '{}'::jsonb,
    '{}'::jsonb
  )
on conflict (id) do update
set
  client_id = excluded.client_id,
  title = excluded.title,
  bank_name = excluded.bank_name,
  process_number = excluded.process_number,
  contract_number = excluded.contract_number,
  claim_type = excluded.claim_type,
  stage = excluded.stage,
  status = excluded.status,
  amount_in_dispute = excluded.amount_in_dispute,
  estimated_value = excluded.estimated_value,
  main_thesis = excluded.main_thesis,
  legal_risk = excluded.legal_risk,
  suggested_strategy = excluded.suggested_strategy,
  owner_label = excluded.owner_label,
  niche = excluded.niche,
  linked_documents = excluded.linked_documents,
  linked_tasks = excluded.linked_tasks,
  linked_deadlines = excluded.linked_deadlines,
  lexia_insights = excluded.lexia_insights,
  workflow_state = excluded.workflow_state,
  checklist_state = excluded.checklist_state,
  updated_at = timezone('utc', now());
