insert into public.documents (
  id,
  tenant_id,
  client_id,
  case_id,
  file_name,
  original_file_name,
  document_type,
  category,
  tags,
  ai_status,
  summary,
  page_count,
  uploaded_at,
  preview_label,
  actions
)
values
  (
    'doc-001',
    '11111111-1111-1111-1111-111111111111',
    'cl-001',
    'case-101',
    'contrato-financiamento-veiculo-mariana.pdf',
    'contrato-financiamento-veiculo-mariana.pdf',
    'Contrato bancario',
    'contrato',
    '["revisional","seguro","CET"]'::jsonb,
    'analyzed',
    'Contrato com indicios de seguro embutido e clausulas com impacto no CET total.',
    18,
    '2026-04-02',
    'Preview pendente do contrato com clausulas destacadas.',
    '["Analisar com IA","Resumir","Extrair tese","Gerar peca","Buscar jurisprudencia"]'::jsonb
  ),
  (
    'doc-002',
    '11111111-1111-1111-1111-111111111111',
    'cl-001',
    'case-101',
    'planilha-parcelas-mariana.xlsx',
    'planilha-parcelas-mariana.xlsx',
    'Planilha',
    'financeiro',
    '["parcelas","juros","memoria-calculo"]'::jsonb,
    'needs_review',
    'Planilha utilizada para comparar parcelas contratadas e encargos efetivamente pagos.',
    4,
    '2026-04-03',
    'Preview pendente da memoria de calculo e das parcelas.',
    '["Analisar com IA","Resumir","Extrair tese"]'::jsonb
  ),
  (
    'doc-003',
    '11111111-1111-1111-1111-111111111111',
    'cl-002',
    'case-205',
    'comprovantes-pix-carlos.pdf',
    'comprovantes-pix-carlos.pdf',
    'Comprovante bancario',
    'fraude',
    '["pix","fraude","comprovantes"]'::jsonb,
    'analyzed',
    'Comprovantes das transferencias e registros de movimentacao vinculados ao golpe via PIX.',
    9,
    '2026-04-04',
    'Preview pendente dos comprovantes e da cronologia do evento.',
    '["Analisar com IA","Resumir","Buscar jurisprudencia"]'::jsonb
  ),
  (
    'doc-004',
    '11111111-1111-1111-1111-111111111111',
    'cl-003',
    'case-311',
    'ccb-capital-giro-araujo.pdf',
    'ccb-capital-giro-araujo.pdf',
    'CCB',
    'contrato',
    '["capital-giro","ccb","capitalizacao"]'::jsonb,
    'analyzed',
    'Cedula de credito bancario com pontos sensiveis sobre capitalizacao mensal e encargos remuneratorios.',
    22,
    '2026-04-01',
    'Preview pendente da CCB com clausulas sensiveis destacadas.',
    '["Analisar com IA","Resumir","Extrair tese","Gerar peca","Buscar jurisprudencia"]'::jsonb
  ),
  (
    'doc-005',
    '11111111-1111-1111-1111-111111111111',
    'cl-003',
    'case-312',
    'notificacao-negativacao-araujo.pdf',
    'notificacao-negativacao-araujo.pdf',
    'Intimacao',
    'cobranca',
    '["negativacao","urgencia","cobranca"]'::jsonb,
    'not_analyzed',
    'Notificacao de negativacao vinculada ao contrato principal com potencial para pedido urgente.',
    3,
    '2026-04-05',
    'Preview pendente da notificacao de negativacao.',
    '["Analisar com IA","Resumir","Gerar peca"]'::jsonb
  )
on conflict (id) do update
set
  client_id = excluded.client_id,
  case_id = excluded.case_id,
  file_name = excluded.file_name,
  original_file_name = excluded.original_file_name,
  document_type = excluded.document_type,
  category = excluded.category,
  tags = excluded.tags,
  ai_status = excluded.ai_status,
  summary = excluded.summary,
  page_count = excluded.page_count,
  uploaded_at = excluded.uploaded_at,
  preview_label = excluded.preview_label,
  actions = excluded.actions,
  updated_at = timezone('utc', now());
