insert into public.procedural_updates (
  id,
  tenant_id,
  process_id,
  case_id,
  client_id,
  occurred_at,
  movement_type,
  source_court,
  source_label,
  raw_movement,
  operational_summary,
  criticality,
  clara_impact_summary,
  clara_caution,
  clara_next_actions
)
values
  (
    'upd-101',
    '11111111-1111-1111-1111-111111111111',
    'proc-101',
    'case-101',
    'cl-001',
    '2026-04-09',
    'Despacho',
    'TJSP',
    'Portal TJSP',
    'Vistos. Intime-se a parte autora para complementar memoria discriminada do calculo e esclarecer composicao dos encargos impugnados.',
    'O juizo cobrou detalhamento tecnico da planilha revisional antes de avancar na apreciacao.',
    'high',
    'O caso continua bem posicionado, mas a forca da tese depende agora de uma memoria de calculo mais didatica e tecnicamente robusta.',
    'Se a resposta sair generica, o pedido liminar pode perder tracao logo no primeiro filtro do juizo.',
    '["Revisar memoria de calculo", "Evidenciar CET e seguro embutido", "Preparar resposta objetiva ao despacho"]'::jsonb
  ),
  (
    'upd-205',
    '11111111-1111-1111-1111-111111111111',
    'proc-205',
    'case-205',
    'cl-002',
    '2026-04-09',
    'Certidao',
    'TJRJ',
    'Portal TJRJ',
    'Certifico a ausencia de documento complementar indispensavel ao regular prosseguimento da demanda.',
    'Ainda falta prova essencial para liberar o protocolo do caso de fraude PIX.',
    'medium',
    'O impacto juridico ainda e controlavel, mas o caso segue travado enquanto a prova faltante nao entrar.',
    'Nao vale sofisticar a narrativa agora; o gargalo segue sendo documental.',
    '["Cobrar documento complementar", "Atualizar cronologia do golpe", "Checar prontidao da inicial"]'::jsonb
  ),
  (
    'upd-311',
    '11111111-1111-1111-1111-111111111111',
    'proc-311',
    'case-311',
    'cl-003',
    '2026-04-10',
    'Ato ordinatorio',
    'TJMG',
    'Portal TJMG',
    'Intime-se a parte autora para conferencia dos anexos empresariais e regularidade da representacao documental.',
    'A movimentacao nao muda a tese, mas exige saneamento de anexos antes do protocolo final.',
    'low',
    'O caso segue forte. O risco imediato nao e juridico, e sim operacional por eventual erro documental.',
    'Um detalhe societario mal anexado pode atrasar um caso que ja esta maduro para ingresso.',
    '["Conferir contrato social", "Validar poderes de representacao", "Liberar protocolo apos saneamento"]'::jsonb
  ),
  (
    'upd-312',
    '11111111-1111-1111-1111-111111111111',
    'proc-312',
    'case-312',
    'cl-003',
    '2026-04-08',
    'Despacho',
    'TJMG',
    'Portal TJMG',
    'Intime-se a parte autora para apresentar prova complementar da negativacao e do dano operacional alegado.',
    'A tutela depende agora de prova objetiva da restricao e do impacto concreto na operacao da empresa.',
    'high',
    'A tese continua boa, mas o caso pede prova mais incisiva para sustentar urgencia e dano moral empresarial.',
    'Sem prova forte da restricao, o pedido de urgencia pode perder aderencia.',
    '["Reunir prova da negativacao", "Documentar impacto comercial", "Reforcar pedido de tutela"]'::jsonb
  )
on conflict (id) do update
set
  process_id = excluded.process_id,
  case_id = excluded.case_id,
  client_id = excluded.client_id,
  occurred_at = excluded.occurred_at,
  movement_type = excluded.movement_type,
  source_court = excluded.source_court,
  source_label = excluded.source_label,
  raw_movement = excluded.raw_movement,
  operational_summary = excluded.operational_summary,
  criticality = excluded.criticality,
  clara_impact_summary = excluded.clara_impact_summary,
  clara_caution = excluded.clara_caution,
  clara_next_actions = excluded.clara_next_actions,
  updated_at = timezone('utc', now());
