insert into public.official_diary_publications (
  id,
  tenant_id,
  process_id,
  case_id,
  client_id,
  published_at,
  source_court,
  source_label,
  title,
  raw_context,
  banking_summary,
  required_action,
  urgency,
  responsible_lawyer,
  suggested_task_title,
  suggested_task_description
)
values
  (
    'pub-101',
    '11111111-1111-1111-1111-111111111111',
    'proc-101',
    'case-101',
    'cl-001',
    '2026-04-08',
    'TJSP',
    'DJE TJSP',
    'Intimacao para complemento da memoria de calculo',
    'Fica a parte autora intimada para, no prazo legal, complementar memoria discriminada do calculo e esclarecer a composicao dos encargos cobrados no contrato.',
    'A publicacao reforca a necessidade de consolidar CET, parcelas efetivas e venda casada para sustentar a revisional com maior seguranca.',
    'Juntar planilha revisional consolidada e revisar a narrativa de encargos abusivos antes da proxima manifestacao.',
    'high',
    'Dra. Helena Siqueira',
    'Responder intimacao sobre memoria de calculo',
    'Preparar resposta com memoria de calculo detalhada, CET, seguro embutido e demonstrativo dos encargos questionados.'
  ),
  (
    'pub-205',
    '11111111-1111-1111-1111-111111111111',
    'proc-205',
    'case-205',
    'cl-002',
    '2026-04-09',
    'TJRJ',
    'DJE TJRJ',
    'Certidao de pendencia documental para distribuicao',
    'Certifico que a inicial depende da juntada de documento complementar para regular prosseguimento do pedido apresentado pela parte autora.',
    'No contexto de fraude PIX, a falta de documento formal ainda enfraquece a linha probatoria e impede o ingresso seguro da acao.',
    'Cobrar documento pendente do cliente e validar se a narrativa cronologica esta pronta para protocolo.',
    'medium',
    'Dr. Caio Nascimento',
    'Destravar documento pendente para fraude PIX',
    'Acionar o cliente, receber o documento complementar e liberar a estrutura final da inicial.'
  ),
  (
    'pub-311',
    '11111111-1111-1111-1111-111111111111',
    'proc-311',
    'case-311',
    'cl-003',
    '2026-04-07',
    'TJMG',
    'DJE TJMG',
    'Ato ordinatorio para conferencia de anexos de consignado',
    'Intime-se a parte autora para confirmar regularidade dos anexos de consignado e eventual extrato do beneficio nos autos.',
    'A publicacao nao altera a tese de desconto indevido, mas exige saneamento documental antes do protocolo ou da continuidade da medida.',
    'Conferir contrato consignado, extrato e prova do desconto antes do proximo movimento da equipe.',
    'medium',
    'Dra. Julia Ramalho',
    'Conferir anexos do cartao consignado',
    'Validar extrato e contrato obrigatorios para manter o caso apto ao protocolo.'
  ),
  (
    'pub-312',
    '11111111-1111-1111-1111-111111111111',
    'proc-312',
    'case-312',
    'cl-003',
    '2026-04-07',
    'TJMG',
    'DJE TJMG',
    'Despacho exigindo prova complementar da busca e apreensao',
    'Intime-se a parte autora para apresentar prova documental complementar acerca da mora e da posse do veiculo, no prazo assinalado.',
    'A tese permanece boa, mas a tutela depende de prova objetiva da mora controvertida e da preservacao do bem.',
    'Separar notificacao de mora, comprovantes e demonstracao da posse do veiculo para reforcar a urgencia.',
    'high',
    'Dra. Julia Ramalho',
    'Montar prova complementar da busca e apreensao',
    'Reunir prova da mora e da posse do veiculo para sustentar tutela e preservacao do bem.'
  )
on conflict (id) do update
set
  process_id = excluded.process_id,
  case_id = excluded.case_id,
  client_id = excluded.client_id,
  published_at = excluded.published_at,
  source_court = excluded.source_court,
  source_label = excluded.source_label,
  title = excluded.title,
  raw_context = excluded.raw_context,
  banking_summary = excluded.banking_summary,
  required_action = excluded.required_action,
  urgency = excluded.urgency,
  responsible_lawyer = excluded.responsible_lawyer,
  suggested_task_title = excluded.suggested_task_title,
  suggested_task_description = excluded.suggested_task_description,
  updated_at = timezone('utc', now());
